name: W poniedzialek znowu do roboty
title: GitHub pages
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: vistula

# logo: "/assets/images/Morris_badge.png"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KatarzynaJonczyk/3Dprinter_manual"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This manual uses information and pictures provided by Sinterit. They can be found at<a href=\"https://sinterit.com\">sinterit.com</a>"